# Generated by Django 3.2 on 2021-05-02 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchifyApp', '0006_alter_tag_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='tag_name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_post',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_posts', to='searchifyApp.tag'),
        ),
    ]
