# Generated by Django 3.2 on 2021-05-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchifyApp', '0009_auto_20210502_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='No Images', upload_to='images/'),
        ),
    ]
