# Generated by Django 3.2 on 2021-05-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchifyApp', '0002_auto_20210430_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(default=None, max_length=32, unique=True),
        ),
    ]
