# Generated by Django 3.2 on 2021-05-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchifyApp', '0007_auto_20210502_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
