# Generated by Django 3.2 on 2021-05-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchifyApp', '0008_alter_tag_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_name',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_post',
            field=models.ManyToManyField(related_name='tagged_posts', to='searchifyApp.Post'),
        ),
    ]
