# Generated by Django 3.2 on 2021-05-05 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchifyApp', '0010_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likers',
        ),
    ]
